DROP USER SIT_XM128_TRADE CASCADE;

CREATE USER SIT_XM128_TRADE
IDENTIFIED BY VALUES 'SIT_XM128_TRADE'
DEFAULT TABLESPACE TRADE
TEMPORARY TABLESPACE TEMP
PROFILE DEFAULT
ACCOUNT UNLOCK;


GRANT CONNECT TO SIT_XM128_TRADE;
GRANT IMP_FULL_DATABASE TO SIT_XM128_TRADE;
GRANT PLUSTRACE TO SIT_XM128_TRADE;
GRANT RESOURCE TO SIT_XM128_TRADE;
ALTER USER SIT_XM128_TRADE DEFAULT ROLE ALL;

GRANT ADVISOR TO SIT_XM128_TRADE;
GRANT UNLIMITED TABLESPACE TO SIT_XM128_TRADE;

GRANT EXECUTE ON SYS.DBMS_FGA TO SIT_XM128_TRADE;
GRANT READ, WRITE ON DIRECTORY SYS.MY_EXPDP_DUMP TO SIT_XM128_TRADE;

alter user SIT_XM128_TRADE identified by SIT_XM128_TRADE;
