`T_CLIENT_INFO``T_CLIENT_INFO`


SELECT COUNT(*) FROM T_SECURITY_OPERATOR_STEP
WHERE OSN LIKE 'md5test%'

SELECT * FROM T_SECURITY_OPERATOR_STEP

SELECT COUNT(*) FROM T_SECURITY_OPERATOR_STEP


DELETE FROM T_SECURITY_OPERATOR_STEP
WHERE OSN LIKE 'md5test%'

SELECT COUNT(*) FROM T_SECURITY_OPERATOR_STEP_RECEIVE 
WHERE OSN LIKE 'md5test%'

SELECT * FROM T_SECURITY_OPERATOR_STEP_RECEIVE 
WHERE OSN LIKE 'xcaaslichen%'

SELECT SLEEP(0.1),user_name FROM T_SECURITY_OPERATOR_STEP 
WHERE OSN LIKE 'xcaaslichen%' AND SOURCE_NO IN ('121', '128')


DELETE FROM T_SECURITY_OPERATOR_STEP
WHERE OSN LIKE 'xcaaslichen%' 

DELETE FROM T_SECURITY_OPERATOR_STEP_RECEIVE
WHERE OSN LIKE 'xcaaslichen%'

SHOW VARIABLES LIKE 'slow%'

SHOW VARIABLES LIKE 'long%'

SHOW VARIABLES LIKE 'table_type';


SHOW CREATE TABLE T_SECURITY_OPERATOR_STEP;

SHOW PROCEDURE STATUS;


CALL p_proc_trail("123");
