USE INETACT;
USE inetact-test;
USE mysql;
DELETE FROM T_MOBILE_BIND_INFO WHERE USER_NAME LIKE 'lichen'

SELECT * FROM T_MOBILE_BIND_INFO 
	WHERE USER_NAME IN ('hsxww0072') 
	
	SELECT * FROM T_MOBILE_BIND_INFO 
	WHERE USER_NAME IN ('zhongtai002','huaan002','wanlian002')
	AND create_time LIKE '2016-08-08%';
	

SELECT * FROM T_SRV_EXEC_REQUEST
WHERE REQUEST_TIME > '2016-7-21' AND
DONEE_NAME = 'test测试_20175623'


SELECT * FROM T_SRV_EXEC_REQUEST;
WHERE 
DONEE_NAME = 'test测试_20175623'


SELECT * FROM T_MOBILE_BIND_INFO ORDER BY id_mobile_bind_info DESC
	WHERE USER_NAME LIKE 'lichen%';
	
SELECT * FROM T_MOBILE_BIND_INFO
WHERE mobile = '35c98c6e717a0d4fd2438f9516a30c33'
AND user_name = 'dzh-crp-sms'

SELECT * FROM T_MOBILE_BIND_INFO
WHERE user_name = 'dzh-crp-sms' ORDER BY id_mobile_bind_info DESC
	
SELECT * FROM T_MOBILE_BIND_INFO 
	WHERE USER_NAME LIKE 'lichen1002%' 
	AND MARK LIKE '135%'

SELECT * FROM T_MOBILE_BIND_INFO_BAK2

SELECT * INTO T_MOBILE_BIND_INFO_BAK2 FROM T_MOBILE_BIND_INFO

INSERT INTO T_MOBILE_BIND_INFO_BAK2 (SELECT * FROM T_MOBILE_BIND_INFO)


DROP TABLE IF EXISTS `T_MOBILE_BIND_INFO_BAK2`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_MOBILE_BIND_INFO_BAK2` (
  `ID_MOBILE_BIND_INFO` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '..',
  `USER_NAME` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT '' COMMENT '...',
  `USER_ID` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '..ID',
  `MOBILE` VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '........',
  `MOBILE_SYM` VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '........',
  `OSN` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '.....',
  `ISN` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '........',
  `MARK` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '3-3-4.....',
  `CHANNEL` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '..',
  `SOURCE_NO` VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '....',
  `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
  `MKT_ACTIVITY_CODE` VARCHAR(200) DEFAULT NULL,
  `REMARK` VARCHAR(2000) DEFAULT NULL COMMENT '备注',
  `URL_CODE` VARCHAR(255) DEFAULT NULL COMMENT '���ýӿ�URL�̱���',
  `SYNC_STATUS` SMALLINT(1) DEFAULT NULL COMMENT '同步状态，0 未同步 1 已同步',
  `EXT_DATA1` VARCHAR(100) DEFAULT NULL,
  `EXT_DATA2` VARCHAR(100) DEFAULT NULL,
  `EXT_DATA3` VARCHAR(100) DEFAULT NULL,
  `EXT_DATA4` VARCHAR(100) DEFAULT NULL,
  `UPT_TIME` DATETIME DEFAULT NULL,
  PRIMARY KEY (`ID_MOBILE_BIND_INFO`),
  KEY `idx_crt_time` (`CREATE_TIME`),
  KEY `idx_mark_mac` (`MARK`,`MKT_ACTIVITY_CODE`),
  KEY `idx_username_mac` (`USER_NAME`,`MKT_ACTIVITY_CODE`),
  KEY `idx_mobile_mac` (`MOBILE`,`MKT_ACTIVITY_CODE`),
  KEY `id_ext_data1` (`EXT_DATA1`),
  KEY `idx_crt_ext_data2` (`EXT_DATA2`) USING BTREE,
  KEY `idx_upt_time` (`UPT_TIME`) USING BTREE
) ENGINE=INNODB AUTO_INCREMENT=11775 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;